#ifndef KEYBOARDS_CHIBIOS_TEST_CHIBIOS_TEST_H_
#define KEYBOARDS_CHIBIOS_TEST_CHIBIOS_TEST_H_

#include "quantum.h"

#define LAYOUT(k00, k01, k02, k03, k04) {{ k00, k01, k02, k03, k04 }}

#endif /* KEYBOARDS_CHIBIOS_TEST_CHIBIOS_TEST_H_ */
